### ISSUE TITLE
cargo run: serde_derive not compiling

### ISSUE THREAD

**Issue by fdlombae** [ZeusWPI/MOZAIC#105]
Running on Ubuntu 17.04, rustc 1.16.0, cargo 0.17.0. (Installed through apt)

On running `cargo run` in botdriver for the first time, 'serde_derive' doesn't compile:

Compiling serde_derive v1.0.15
error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
  --> /home/flor/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.15/src/lib.rs:33:1

33 | extern crate proc_macro;

Probably not related to this project, but can't find much info on this on the interwebs either.

**Comment by Silox** [comment]
Hi @fdlombae ,

I found this comment https://github.com/m4b/bingrep/issues/8#issuecomment-309537714. Seems like the default ubuntu apt version of Rust is too old. I'd try to install a newer rust version, perhaps by running:

> https://doc.rust-lang.org/1.0.0/book/installing-rust.html

**Comment by fdlombae** [comment]
That fixed the problem, thx!
