### ISSUE TITLE
How do we identify bots?

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#106]
As we are starting to evolve into a more serious platform, it might be time to think about how we want to identify a bot. Of course, we just assign them an UID and be done with it, but there are a few details to fill in:

- What is 'a bot'? Are two different versions of the same program the same bot? (i.e. is the UID a function of source code?)
- How do UIDs relate to bot names? We probably want to allow people to name their bots. Are these names purely cosmetic, and if so, do we allow duplicates?
- Should an UID also be an authentication token? (when having a large enough number of possible UIDs, this is secure). This is not an implementation detail because it would require secrecy of the UID.

**Comment by tl3ilaxu** [comment]
I think in practice users will want to train their bots against alternative versions of their bots or older versions. So different source code means different bot I think.

As for naming I would make it cosmetic and unrelated to the id.

**Comment by iasoon** [comment]
@tl3ilaxu what about name uniqueness?

**Comment by tl3ilaxu** [comment]
We don't really need name uniqueness, players are visually identifiable by name and color and that combination will be unique.

**Comment by wschella** [comment]
@tl3ilaxu isn't the color generated from the name? So if the name is the same, so is the color?

**Comment by tl3ilaxu** [comment]
If we use a UID we would use that as the internal identifier.

**Comment by tl3ilaxu** [comment]
Alternatively a internal visualize id could be generated, just seems stupid to have a name restriction that we can avoid in the visualizer.

**Comment by iasoon** [comment]
@tl3ilaxu this is not just about the visualizer, but also about bot ranking tables, "I want to fight that dude", etc.

**Comment by Silox** [comment]
I'm in favor of identifying a bot using a (botname, version)-combination. One person can so add multiple bots, with multiple versions of each bot, while maintaining a clear link between different versions of the same bot.

If a bot's (botname, version)-combination is unique per player, identifying who you want to play is in any case clear when user, botname and version are shown.

**Comment by wschella** [comment]
How do we deduct the version? Is every submission a new bot? I feel like if players want versioning, they can add it themselves, and it will be more flexible for them anyway.

**Comment by tl3ilaxu** [comment]
You would indeed like to be able to say: show me all iepoev bots and then get all uploaded version of that bot. But do we ask users to identify themselves? How do we differentiate between bots with the same name form different uploaders? Also users should not be responsible for tracking the version, maybe just timestamp bots?

**Comment by Silox** [comment]
I see "version" in a more broad manner than just a number. I could for example make a "hex" or "quad" version of the same bot, depending on how many planets there are.

**Comment by iasoon** [comment]
@Silox Is there an issue with naming your bots SiloxBot-hex and SiloxBot-quad?

**Comment by tl3ilaxu** [comment]
I feel that identifing bots by name is a sure way of making the botpool a mess of horrible bot version naming. I don't think there's an issue with the SiloxBot-hex and SiloxBot-quad naming. BUT i don't think we can trust our users to be consistent with naming making it hard for users to find newest versions of bots.

Example: botAFinal, botaFinalfinal, Latestbota etc...

**Comment by iasoon** [comment]
@tl3ilaxu I would assume that if you want to update your bot, you just re-upload it and the previous version is overwritten. These versions are for maintaining multiple bots concurrently (for example, using a different strategy).

**Comment by tl3ilaxu** [comment]
@iasoon so actualy it boils down to this. Do we store multiple versions of the same bot? Yea or nay. I think keeping track of multiple versions of the same bot is a hassle we don't need. 
So if we go that route I'm all for using the name of the bot as id, but I would also like to see the botnames related to the user that uploads them. So names of bots are only unique per user, names can have duplicates in the botpool.

**Comment by Silox** [comment]
Don't you need to store them from a history point of perspective? If LoxBot-v1 loses against LelBot-v1, and later LoxBot-v2 wins against LelBot-v1, I'd like to be able to see that it was LoxBot-v1 that lost and not LoxBot-v2.

**Comment by timodw** [comment]
It would be handy and not all that hard to implement to just keep a counter for each bot, so you know that LoxBot (3) is a newer version than LoxBot (2)

**Comment by iasoon** [comment]
@Silox You are right, and we would most certainly want to keep this 'bot history', but it would not be neccesary to identify a bot. Once LoxBot v2 gets updated, LoxBot v1 will never play a match again. We will of course annotate this in historical matches.

**Comment by Silox** [comment]
But if you implement a counter, you could implement it is a string and let people choose the version themselves. And then we're back to https://github.com/ZeusWPI/MOZAIC/issues/106#issuecomment-333307105

**Comment by tl3ilaxu** [comment]
So summarizing: we keep botnames unique per user in the botpool. When a user uploads a bot with the same name we overwrite the old one in the botpool but keep the bot archived. Sound about right?

**Comment by wschella** [comment]
Just to be clear, are we talking about our small tournament plans for current blockly setup, or long-term plans for a decent gameserver, or both?

**Comment by iasoon** [comment]
@wschella long-term plans.

Important detail: when I upload a new version of my ProBot3000, will he have the same UID as the previous version or a different version?

**Comment by tl3ilaxu** [comment]
Do we want users to be able to browse the code of previous versions of bots on our server or do we keep users responsible for their own bot code history.

For the former we would need new ids per bot, for the latter we would keep the same id and overwrite the old entry.

**Comment by wschella** [comment]
I'm a bit confused. If these are long-term plans, why are we talking about uploading? In our long term goal, the source code or bot used is invisible and unavailable to the game-server. We can not archive a bot. A bot from the servers perspective is a socket to send data tho that will reply to given prompts. Any data about which bot is which, and what version it is running is completely supplementary and unverifiable by the game server. 

We can choose to implement this, and let users differentiate between bots and versions manually, but that information would be match-specific and unverifiable by us. A 'bot' would then be an aggregate collection of matches with the same bot-name given by the player.

So i would like to pose some new questions:
 - Do we allow multiple bots in the ranking per player? Since this is aggregate data over matches, we could support this. But we would need to trust our players that these are actually different/same bots.
 - If we do, do we allow multiple bot versions per bot?
 - If we do, wouldn't old bots become stale and irrelevant quickly? Since the user would have to actively let his old bots play, you can't compete against them.

**Comment by wschella** [comment]
To give some context, in the architecture, the only place for a botpool is a server that pretends to be a client. This was previously thought about as a way of dealing with the limited amount of online users.

Viewing it in this light, I see the botpool more as 'keep-your-bot-online-service' than as a complex bot-management system. We do still want a decent bot-managament system in far future, but I feel this discussion is extremely premature. 

To rephrase again, what way do we want to abstract?
 - To the game server, the concept of a user and a bot are the same, allowing only 1 bot per user.
 - To the game server, only the concept of a bot exists, and a player is an abstraction that lays outside of the gameservers scope.
 - Both the concept of a bot and a user exist, and they are not the same, in which case I wonder how things will work.

Personally I feel most like the second solution, in that the game server only knows a bots. Bots then have a UID that does not change (for example when versioning). If a player wants to distinct 2 bots, they both need a UID. 

As proposed by @tl3ilaxu, if botnames are unique per player, we could take the (playername, botname) tuple as a UID. But I propose keeping both unrelated to the gamservers internal workings, and making the mapping to a visual user friendly name on a higher abstraction level.

**Comment by wschella** [comment]
And finally to answer the original questions:

 - A bot is like a player. It makes progress and changes, it gets better or worse relative to the competition, but it keeps the same identity. Versioning would just be a supplement to the current logic, and an abstraction of the time + source code, decided by the player. It would only serve an informational use, not a functional one. So no, the UID is not a function of the source code, and should remain constant if the user considers a bot still the same bot. It's a bit like how you could replace a cars engine and seats and windows, but to the driver it would still be the same car.

- From a gameserver perspective, there is no such thing as a botname. So yes, these names are purely cosmetic, and should be implemented in higher abstraction level or other component. They should definitely be unique per player, whether they should be globally unique I have no strong opinions.

- UID's should not be an authentication token. It should only serve as the identification of a bot, and will be passed around in all non-user-facing components, and will be mapped to/from in all user-facing components. Keeping this a secret would complicate things significantly in components that do not need it.

**Comment by iasoon** [comment]
@wschella we are talking about uploading because it is the current state of matters, and when this is not required anymore we will still offer a hosting option. But you are right that is steering the discussion in a wrong direction.

Entirely agree with your last post.

**Comment by iasoon** [comment]
Feel free to re-open if you have more input.
