### ISSUE TITLE
Just review every unwrap() please

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#119]
Every unwrap() on something that only slightly interfaces with something user related should have decent error handling instead of just panicking.

**Comment by iasoon** [comment]
I kind of disagree.
You are referring to a lot of  temporary code (which should be commented), and lots of unwraps which should (provably) never happen.
Error messages are only useful when an user causes the errors. For other cases, RUST_BACKTRACE exists.

**Comment by wschella** [comment]
in "_that only slightly interfaces with something user related_" there's the option that users cause the error. When we are dealing with an MVP shouldn't we exactly _slap baind-aids_? These errors are easy to find out as a dev with some insight in the code, but when a new dev tries to get in and faces these things, they are very demotivating. Adding a simple error message explaining what just happened (eg: #118 and #117 ) makes a major difference without any work.

When our own code causes the error, I completely agree with your last input.

**Comment by iasoon** [comment]
It would be good to handle this simultaneously with implementing proper logging, as per #124 will conclude.

**Comment by iasoon** [comment]
Blocked until we decide on a proper way to log the errors that occur

**Comment by wschella** [comment]
Handled in #124
