### ISSUE TITLE
Pick a game

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#13]
Pick a 'test game' to implement. The game should be easy to write a bot for, but keep it challenging so that we don't get bored.

## Proposal

[Planet Wars](https://github.com/eonarheim/planet-wars-competition) with an added rule:
- Each player can only have one fleet in transit at any given moment.
  This rule greatly reduces the complexity of the game, yet does not alter its core principles.

**Comment by wschella** [comment]
From the MVP:
```
Proposition: [Planet Wars](https://github.com/eonarheim/planet-wars-competition) with an added rule:
Each player can only have one fleet in transit at any given moment. This rule greatly reduces the complexity of the game, yet does not alter its core principles (please speak up if you think it does!).
Arbiter
```

**Comment by NoctuaNivalis** [comment]
Proposal: mobile jousting.

On a 2D grid, with free space and obstacles (only some, or a complete maze for harder games), each player controls a jousting knight. A knight occupies 2 spaces: the body and a lance. Try to pierce (overlap) the other players body with your lance while avoiding him doing the same. Caveat: knights move two square forward in each turn, but only one square left/right/backwards. Turning 90 degrees also costs a turn and you can only turn when unobstructed (if you turn left, the square on your left and your front left should both be empty).

This game can be extended later with multiple knights for each player.

**Comment by iasoon** [comment]
@NoctuaNivalis That certainly sounds like a fun game! However, it doesn't sound trivial to write a simple bot for this game, contrary to the Planet Wars proposal. That makes it less of a good fit for our introduction day MVP, which is aimed at derps.

**Comment by NoctuaNivalis** [comment]
If it's for the real competition, please add infantry, archers and catapults as well.

**Comment by iasoon** [comment]
We're picking [Planet Wars](https://github.com/ZeusWPI/MOZAIC/blob/master/docs/planetwars.md).
