### ISSUE TITLE
Create config form in client

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#133]
Currently a config looks a bit like this:
```
{
    "players": [
        {
            "name": "bert",
            "command": "python3",
            "args": ["../games/planetwars/bots/simplebot/simple.py"]
        },
        {
            "name": "timp",
            "command": "python3",
            "args": ["../games/planetwars/bots/simplebot/simple.py"]
        }
    ],
    "game_config": {
        "player_map": {
            "bert": "player_1",
            "timp": "player_2"
        },
        "map_file": "../games/planetwars/maps/hex.json",
        "max_turns": 500
    },
    "log_file": "gamelog.json"
}
```

Now, in the client, we would like to provide some visual interface, a form, to create this a bit more pretty.
So, create a form that makes a config like this.

### Steps to succes
- Create a new React component that contains this form
- Add some form fields
- Create an internal representation of a gameconfig
- Add a button that saves form data to internal config
- Save config to filesystem

**Comment by iasoon** [comment]
Resolved in #137 .
