### ISSUE TITLE
Filer component

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#140]
Tracking issue for the filer component.

Currently, it is best described on the [game server wiki page](https://github.com/ZeusWPI/MOZAIC/wiki/Game-server).

**Comment by iasoon** [comment]
We talked a few times about running the game server locally. I'm assuming we'd prefer not requiring the user to set up a database, instead working the way our game server does right now. This difference would be in the filer component. How do we handle this? Use two different filer implementations for a "local build" and a "server build"? 

How do we achieve this without causing duplication in the components that use the filer?

**Comment by wschella** [comment]
I've been thinking about the problems ahead regarding duplication of server and client code. It seems that if we want decent feature-parity for running local and online games, we suddenly have a lot of uncertainty about the requirements and inputs, and on top, _all_ components now need to flawlessly work on a multitude of OS's, where before this was limited to only a couple of components. 

I propose 2 different implementations, since I feel like the what the filer needs to do on the server will not reflect decently on what it will do on the client (where it will probably be a smaller component), and the components that use the filer will differ between client/server anyway.

**Comment by iasoon** [comment]
The local implementation will probably not be much larger than our current code base, correct? We don't need a lobby nor a matchmaker, since that is handled by the client now.

I guess we still want to run the bots over TCP, though, to avoid complication and always have the client run bots. That means we will need a local server in any case. Do we want this to be an one-shot server, or one that stays alive and can be reused? I think the latter option would allow the most code reuse, but would also be the more complex option.

What do you mean by uncertainty about requirements and inputs?

**Comment by wschella** [comment]
I mean that we haven't thought well about how we want our local game implementation to work, where it fits in the total client, how the flow will go. So we don't know very well about how the filer should function locally.

In agree about always running bots over TCP (will be consistent with possible LAN support). My intuition seems to go for 'one-shot server'.

**Comment by iasoon** [comment]
While definitely simpler, I'll be devil's advocate for a minute, and defend the fully enabled server.
A client could expose all bots it knows how to run as 'ready to play' to a local server, and place them in the lobby, in the same way our bot nursery would (perhaps we can reuse code?). This allows you to use the same interface for challenging / playing a quick match between your local bots as you would use on the remote server, which is both consistent as way less effort for us, and people running their own game on MOZAIC.

**Comment by wschella** [comment]
You might have point. Code reuse will be larger for the client itself, as the only distinction between local and remote would be the were the server is hosted. I'm assuming we will come to meet some different requirements for local and remote servers, but I guess that's a problem for later.

Small note: we should have distinct terms for local play on single computer, and local play over a local network (although in this proposal it doesn't really matter much).

**Comment by iasoon** [comment]
@wschella as for terminology, that would be local / LAN / network, I think.

There will probably indeed be different requirements, but it would be nice if these would not have any effect on the client, so that we can keep it lean. You should be able to use the full MOZAIC game server, or a custom stripped-down build for local play, without changing anything in your client.

Authentication is another issue that comes to mind (authorization and identification are still required).
But for the filer, I guess we'll aim for writing the fully functional server first, and strip it down for convenience afterwards. That would answer the question about the filer component specifically.

I opened #141 to continue the discussion about the custom server build.

**Comment by iasoon** [comment]
We decided on resolving this by having a separate game server and matchmaker, where the game server is the 'lean' part, and the matchmaker does all bookkeeping and heavy lifting.
