### ISSUE TITLE
Simplify expedition visuals

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#142]
We shouldn't really do fancy visuals for the expeditions. They don't contribute much, and I'm thinking they are slowing down the rendering quite a lot, since were rendering hundreds of them at the same time on large maps, and they're quite complex svg's.

**Comment by iasoon** [comment]
A simple triangle might be a good option, since it's a single polygon and still conveys all information (like direction).

Ideally we'd be able to switch to the fancy visual once past a certain zoom level, imo.

**Comment by iasoon** [comment]
@tl3ilaxu are you still considering finishing that webgl visualizer port? If so, I think we'd better put resources there than on issues like this.

**Comment by tl3ilaxu** [comment]
@iasoon yes and yes

**Comment by wschella** [comment]
Handled in #158
