### ISSUE TITLE
Time-outs

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#153]
Thanks to @ajuvercr , we are getting close to a nicely abstracted game implementation. However, we still lack an essential feature: time-outs.

@ajuvercr, can you look into how time-outs fit into the abstractions you made (especially the step lock)? If you can figure out an API, we can wire it up to tokio together.

**Comment by ajuvercr** [comment]
@iasoon What do you mean with "figure out an api"?
Wiring it up to Tokio should be easy right? Just check each time, has there been a time-out?

**Comment by iasoon** [comment]
@ajuvercr something to wire up to tokio, basically. Like a method to call when a timeout happens, and a way for a game implementation to set timeouts, yada yada. Just 'make it work'!

As for the tokio part, you're right, it shouldn't be too hard, but I'll happily assist there since I'm more familiar with it :)

**Comment by ajuvercr** [comment]
What is the appropriate action when the initial 'connection' time-out happens? Is this either:

1. Stop the game and there is no winner.
2. Everybody that connected wins.
3. Something else

Personally I think option 1 is the most appropriate.

**Comment by ajuvercr** [comment]
There is a small problem with late coming commands, commands that were actually intended for the previous turn. Normally this only has impact on a small portion of commands, but if you are playing against people far away this could be a problem.
It is possible to make this problem smaller by adding a timestamp to every command, so the lock_step can check if the command is not intended for the previous turn and otherwise discard it.

**Comment by iasoon** [comment]
@ajuvercr It would be better to add a turn number to each command and state update.

**Comment by wschella** [comment]
@ajuvercr, i agree with ilion that associating a turn number might be more practical. 
What exactly do you mean with initial connection time-out? The connections that are required to initialize and start the game? In that case, i agree with choosing point 1, cause I assume the already connected players have not received specific game info yet.

**Comment by iasoon** [comment]
As for turn numbers, I opened #156, and I suggest considering that as 'out of scope' for this issue.

An issue with having no winner is that it could be used to forfeit matches (for example against a stronger player), depending on how the ranking code is implemented.
A better idea might be to have a separate status for this. Now might be a good time to draft an RFC for game exit statues.

**Comment by wschella** [comment]
@iasoon I think it's important that clients have received no game information yet, and as such forfeiting isn't rational. If they have received game information already, it's for the game implementation to decide.

**Comment by wschella** [comment]
@iasoon, your opponent _is_ game information

**Comment by iasoon** [comment]
@wschella Agreed, but are we certain that zero information is exchanged before the actual game starts? I feel it is better to be safe than sorry.

**Comment by wschella** [comment]
Remember that additional exit types make the ranker and matchmaking more complex. Altough that will be worth it in some cases. We could also take into account people trolling others by intentionally disconnecting during this fase, altough that might be premature

**Comment by iasoon** [comment]
@wschella I don't think it makes the matchmaker more complex, since you can trivially map multiple exit statusses to the same action (for example, give somebody points if he wins, in all other cases do nothing). I'm in favour for an expressive protocol here.

But more importantly, what's the status on this @ajuvercr ?

**Comment by iasoon** [comment]
Time-outs """work"""
