### ISSUE TITLE
Client/Server syncing

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#156]
As @ajuvercr pointed out, there is a slight issue with client-server synchronisation when using the current communication scheme. The issue occurs when the  command for a previous turn is received when the game server has already stepped, causing an unintentional command to be executed.

I think the best abstraction for this issue would be an abstraction over the request/response pattern:
- The game implementation calls the method `request(client, message, timeout)`
- A message containing a request number is sent to the client
- Once a message containing that request number is received, control is handed back to the game implementation.

Of course, one could wait for multiple requests to finish before continuing, for example for all players to choose their move. So, this scheme would be a generalization over the `StepLock` we have now.

The main question is how this should fit in the current design. I think it is clear that this is not something that happens on a framework level, since that would be limiting in many ways. It should be an util, on the same level as the `StepLock` we use now. _This means that we cannot leverage the MOZAIC protocol for this, and we have to somehow get this request number into the game protocol._ I'm not sure how we can do this in a hassle-free way. Suggestions?

As for the client-side of things: I imagine lines could be blurred a bit here, either handling requests in the client or bot, depending on the specific needs the game implementer has.

**Comment by wschella** [comment]
Just to throw some ideas around:
 - Our util implementations (like StepLock) could have their own protocol as well, nested within the MOZAIC protocol, and wrapping the game protocol. Serialization will be easy, as we have access to the full 'message'. For MOZAIC as framework, this wouldn't change anything.
- I had another idea but it doesn't make sense (we can't really put it in the game protocol can't we).

**Comment by iasoon** [comment]
This is something we want in the long term, but let's ask the acute question: Do we want a turn number in the planetwars protocol to prevent desynchronisation? If so, I'd just do that in an ad-hoc fashion and have bots put the number in their response (perhaps optionally). If not, we keep the fancyness for a later stage of MOZAIC.

**Comment by iasoon** [comment]
We had some discussion on this today, concluding that in general turn-based games don't have a request/response flow, but rather a request/response/feedback flow. For planetwars, that is gamestate / commands / validation of commands. It seems kind of challenging to me to build an abstraction on this, though, eh, I think?
I guess that all three steps should be logged client-side.
Eh, that kind of makes it easy.
idk I'm tired

**Comment by iasoon** [comment]
The 'hard' part is that this sequence kind of bridges different 'responsibilities': there is interaction between things we previously identified as totally separated 'layers' (game data and metadata such as logging). These three messages would have to be synchronised together, which makes them very much tied to eachother.
@wschella, any thoughts?

**Comment by wschella** [comment]
Quick question while i think further, can we make the validation piggyback on the next gamestate? (That's what we're doing now right?)

**Comment by wschella** [comment]
For clarity, what are we considering as validation, and why do bots need to receive it synced with the other messages?

**Comment by iasoon** [comment]
Validation is 'feedback' on the input your bot provided. Parse errors, logic errors etc. are reported here. For planetwars, that would be a parse error, a dispatch error, or a confirmation of the dispatch. This information is required because it is both the debug information for your bot and needed to construct the game log.

It has to be "synced" with the other messages so that you can determine which command the feedback message describes, just like we need synchronisation to know what game state a command was the reply to. Note that "synchronising" here just means tagging them with a common token (e.g. the turn number).
The reason why this might be though to implement cleanly is that we can't make this token internal to the framework, since the game code will have to parse a reply and send feedback afterwards. For sending the feedback, the user code would need this token. While this is not really an issue, it seems error-prone and a bit dirty. Compare this to a two-way request/reply sequence, where the synchronisation token could be completely internal to the code handling the interaction.

**Comment by wschella** [comment]
I think validation is not relevant for the bot (only the player), which is a small but important distinction! I'mma sleep over it.

**Comment by iasoon** [comment]
I think we certainly want the request/response thing because it is a quite common pattern, it would be ideal if we could do the third message in a higher level protocol.
I was just thinking about the possibly different semantics of a request over a network compared to an acked message. Consider the following situation: a client receives a request, and is then killed for a random reason.
When the client reconnects, the request would not be resent because it is already acked, while desired behaviour would be to resend the request because it was not answered yet. This could be relevant for games with long turns (cfr online chess/risk/go). Do we want to account for this and make requests a primitive in our networking protocol?

**Comment by rien** [comment]
Looks good. I can't think of disadvantages with this approach. This also allows you to create a blocking function that sends a message, waits until a response is received or the timeout passes, and returns the response content.

**Comment by iasoon** [comment]
This RFC has been implemented on the `networking/message-response` branch. It needs some work, but it is functional.
