### ISSUE TITLE
Actual Visualizer goals

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#158]
- [x] We want to be able to resize it
- [x] It should not crash after we load a *NEW* game
- [x] The expedition visuals should be simpler

**Comment by Robbe7730** [comment]
The visualizer should also be able to take a list of "game states" as objects, if possible even one gamestate-object at a time.

**Comment by wschella** [comment]
@tl3ilaxu, can this be closed?

**Comment by tl3ilaxu** [comment]
Think so, unless anyone thinks something is broken?

**Comment by wschella** [comment]
If so, it will deserve it's own issue.
