### ISSUE TITLE
Bot driver: Supervisor

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#16]
The superviser contains the bot driver 'logic'.

This module should couple the ruleset to the bot processes wrapped by #15 .
It is responsible for the flow of the game:
- call out to the ruleset to start a new turn
- communicate to the bots to get their inputs

In short, it glues everything together.

**Comment by wschella** [comment]
To see progress, look at [the botdriver branch](https://github.com/ZeusWPI/MOZAIC/tree/botdriver)
