### ISSUE TITLE
Implement new game log

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#162]
On the `bison-pastures` branch, a new, more complete game log is implemented.
Besides game states, it includes all things that happened in a game, such as the commands sent, whether they were accepted, whether players disconnected, ...

We implemented the log with `slog-json`, which formats log objects as key/value pairs in json.
a `msg`, `timestamp` and `level` are always present, further key/value pairs can be added individually to each log message as we please.

This approach ('structured logging') is useful because it allows us to dump all relevant messages in one log, while still making it easy to find messages about a specific event (for example, all messages related to a specific player: We tag all messages relevant to a player with `client_id: $id`).
An 'issue' might be that while this log is 'structured' in the sense that it is key/value records in json, and thus machine-readable, it is not typed, and the current form might be a little inconsistent and not that much of a pleasure to parse.

Parsing the entire log is key to providing valuable debug information to users.
So, what has to be done?
- We need to decide on a proper format for the structured log that makes it decent to parse in the client
- The new format has to be implemented
- The client has to parse it and display relevant information

A log can be generated by running a game on the `bison-pastures` branch.

**Comment by wschella** [comment]
For the client, parsing should be okay-ish (given it's valid json) if we have somewhat of a 'formal' scheme. An example might do a lot already, we could easily only display the values of which we know the behaviour.

For further development and documentation, a more formal description might be indeed very useful.

**Comment by iasoon** [comment]
Has been done!
