### ISSUE TITLE
Initialize the client with working configs for the testbots

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#164]
We should have some botconfigs for the testbots, fixed in the client, so that users don't need to make them themselves, and they can already view the flow without finalizing a working bot themselves.

**Comment by iasoon** [comment]
How will we distribute these bots?

**Comment by wschella** [comment]
As resources with the clients? I'm not sure exactly how installs will work, but i imagine this is possible. They will need to have python installed tho.

**Comment by wschella** [comment]
Closed in #183
