### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#17]
# Welcome to MOZAIC!
We already did a lot of thinking and wrote a lot of documentation, but ain't nobody got time for that! I made you a quick TL;DR instead.

So, we're writing a programming game! The objective is to write the cleverest bot for some game (think chess or checkers). Of course, to determine which bot is best, we need some infrastructure to run the game. That's what MOZAIC is for!

To get this party started, we'll need:
- A game
  - We'll be playing [Planet Wars](https://github.com/ZeusWPI/MOZAIC/blob/master/docs/planetwars.md).
- Bots
  - External processes that communicate with the game server.
  - Communicate over JSON streams (we'll need a schema: #14)
  - We'll need a test bot for testing: #18 
- A game server to communicate with, which has
  - An implementation of the game rules (#19)
  - A component that wraps bot IO (#15)
  - A 'supervisor', which glues these components together and drives the game. (#16)

We're tracking our progess [here](https://github.com/ZeusWPI/MOZAIC/projects/4).

If you have any questions, need help or emotional support, be sure to ask myself (loser with manbun) or @wschella (tall dude with luscious locks). We're here to help!

**Comment by wschella** [comment]
A current issue that tracks this well/better is #3
