### ISSUE TITLE
Write a test bot

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#18]
Implement a simple bot so that we can test the infrastructure.

Requirements:
- When given a game state on stdin, it outputs a valid command to stdout
(preferably not an empty one, since that does not allow for much testing)

Since the bot is an external process, you can use any language you like, though our lives would probably be easiest when we picked a dynamic language.

**Comment by timodw** [comment]
first implementation in 4ebb061

**Comment by wschella** [comment]
Closed in #20
