### ISSUE TITLE
Implement game rules

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#19]
Yes, this one is quite essential.

The game rules module should:
- Keep track of the game state
- interpret player commands
- step the game state

Note that this module doesn't have to take any actions by itself, it will be driven by the 'supervisor' (#16).

For starters it is fine to silently ignore illegal moves and similar edge cases.

**Comment by wschella** [comment]
This depends on #13 and #14 ofcourse

**Comment by wschella** [comment]
Closed since #50
