### ISSUE TITLE
Differentiate clearly between internal and external config representation

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#213]
The config format for the (Rust) gameserver doesn't really match what we use internally.
We should make this difference clearer in the code.
Eg: Rust uses snake_case and TS pascalCase, and we don't split the program and the args as seperate properties.

**Comment by iasoon** [comment]
Putting this on low priority because _everything_ about the config format is going to change.

**Comment by wschella** [comment]
It is somewhat solved in a not completely horrible way in #205 .
