### ISSUE TITLE
Protobuf logger

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#217]
For #206, the best idea seems to be to create a custom protobuf format for logging. Roughly, this would have some framework-defined log events which the framework will output, and an 'envelope type' for game logging. This allows code reuse in log parsers.

In order to realize this, we'd have to implement our own logging infrastructure. Taking some hints from slog would be useful, but we can't use that library anymore because their structured logging is untyped by design.

**Comment by iasoon** [comment]
@rien and myself whiteboarded a bit around this today, and we are kind of convinced that it would be an improvement over the current situation, mainly because of the strong typing and uniformity.

Point for discussion: do we want to do the actual server logs in protobufs as well for uniformity? (So, not the log for a game, but the log that shows what the server is doing on a higher level, like accepting control connections, creating games, ...)

**Comment by wschella** [comment]
I think the envelope idea fits quite well with the rest of the FW, but as discussed in #156, there needs to be some matching/syncing between the envelope logs and the messages send by bot and game.

**Comment by iasoon** [comment]
An issue with this approach might be that it could void the idea of modularity in MOZAIC, since we will have to determine all possible log messages in advance. We could try to mediate this by either allowing free-form messages, or by trying to draft a logging protocol that should be exhaustive enough (cfr io::Error in Rust maybe).

**Comment by wschella** [comment]
Could this not fit in the enveloppe part? Having a uniform baselayer with known log-messages and a layer on top (wrapped within) more fit for modularity?

**Comment by wschella** [comment]
Is the point of the enveloppe not that we do not need to know the contents (in this case an enveloppe wrapping the modularity layer)?

**Comment by iasoon** [comment]
Yes, but if you have a single envelope type, you still need to know the schema of its contents. If you try to put all the 'modularity' into one envelope, you take away the modularity of the scheme because you still need a joint type definition for the envelope.

**Comment by iasoon** [comment]
I drafted a proposal here: https://github.com/ZeusWPI/MOZAIC/blob/protobuffer-logs/proto/log.proto

**Comment by wschella** [comment]
> The game server does not log anything
Although that seems to fit best in the abstractions for the game server, this feels _fragile_.

**Comment by iasoon** [comment]
This is about match logs, not logging in general. The game server can log as it pleases, but it is not in control of match logs.

**Comment by wschella** [comment]
What i'm saying is it might make sense to duplicate some logs send trough the control channel. As the 'match log' is very broad, and the match owner might be remote. BTW, explicitly tagging with 0 is preferably.

**Comment by iasoon** [comment]
The issue with having the gameserver handle logs is that it would then also need to handle match storage, which we wanted to avoid by logging over a control channel.
We could have all log messages be duplicated to the gameserver log (which will be one log, opposed to match logs which only contain information about one match). So, we would log that we are logging something, basically. This kind of makes sense because we want a gameserver log anyways for no-match related things (such as the gameserver control channel).

The only issue here is that this log will grow very fast on a busy server. Is this a problem?

**Comment by wschella** [comment]
Initially not I think.
We might also make these temporary, as these often serve no UX purpose, and will often only be needed in case things go wrong. To supplement this, we could make this requestable by the game owner, and let them handle it further (allowing the game server to delete it), and/or make it a setting the game owner decides (which would get enabled for debugging).

**Comment by iasoon** [comment]
I think the option to do this should be controlled by the game server, not the match owner.

Do you have any ideas about log levels?

**Comment by wschella** [comment]
I'd mimic existing log libraries, or do you mean component wise?
