### ISSUE TITLE
More information if a bot gives an error

### ISSUE THREAD

**Issue by Immaz** [ZeusWPI/MOZAIC#218]
If a bot gives an error on a certain move, it would be nice if the game state that the bot received as input and on which it crashed would be displayed together with the error message. This would make local debugging a lot easier.
And for local debugging, it would also be nice if in the log of a match, your bot always has id 1, or there is some clearer way to see the id of a certain bot.

**Comment by iasoon** [comment]
@Immaz Sorry for taking so long to follow up with this!

I believe most of these points have been covered by the release of the game log inspector in v0.4 .
That view handles invalid commands, but bot crashes are still a fatal and don't carry too much information. I'll make a separate issue for that.

Can this issue be closed?

**Comment by Immaz** [comment]
Yes of course! Thanks looking into this.

**Comment by iasoon** [comment]
Thank you for taking the time to report the issue!
