### ISSUE TITLE
Game setup for networking

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#227]
We're getting ready for networking support, and we will need to expand the game setup interface to support all new capabilities.
Currently, all games are local. Going forward, all games will be networked, even local play (this will just be local bots connecting to a local server). This means that the gameserver now needs a port on localhost, that can possibly conflict with a running server, so even for local games the user should be able to control this port. (sidenote: how will we handle playing multiple games simultaneously on the same machine? They are going to need a port each. @wschella ?)
Bots connect to a game by opening a tcp connection and then both identifying and authenticating themselves with a token. For bots that are run locally, the client can handle this internally. Remote players will need a way to join somebody else's game by providing the address of the game server and the unique token that was assigned to them. Note that a local game is just a networked game without any remote players.
In the future, we will also have matchmaking services that will handle game creation and token exchange for you. In the client, you should provide "matchmaking parameters" (whichever those will be) and a bot that you want to play with, and the rest should be handled for you.

**Comment by wschella** [comment]
We either choose some port randomly or choose one from some predefined list (nobody will run 10 concurrent matches) and let it be editable by the user in both cases. Does the gamerserver take the port to run as an arg?

**Comment by iasoon** [comment]
@Robbe7730 @myncke Checking the progress that you guys made, I noticed that you added a name field for foreign bots. Is this something we want? An alternative approach would be for bots to send their UUID to the gameserver on connect. These can then be written to the game log. The advantage to this approach is that when you share your logs with other players (for example the other participants), they will be able to identify their bots in the log (and thus display everything correctly).
A disadvantage would be that we still don't have display names for unknown bots.
