### ISSUE TITLE
Proper request/response abstraction

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#255]
This might be really useful in client/server communication.
It should probably be embedded into the event system in order to maintain all guarantees.

Just think about the marshmallows.

**Comment by iasoon** [comment]
Thinking more about this, it might be nice to view _every_ event exchange as a request/response type thing, 'regular' messages having a void return type. This is nice because it will always signal when a request is handled, and we have a built-in way to handle errors in handling events.

**Comment by iasoon** [comment]
I started implementing this anyways. Currently a crappy implementation that only works for client->server requests is implemented on the request-response/again branch.

I believe this is the way we want to move forwards, though.

**Comment by wschella** [comment]
I believe you.
