### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#29]
Basic controls for the visualizer. Should at least have the following buttons:
Play
Pause
Speed controls
Hide controls

Would be nice to keep them small and minimalist. So the viewport can have more screen estate.

**Comment by tl3ilaxu** [comment]
Play/pause button still needs to be toggle at the end of the game.
The turn timer still needs to be bidirectional bound to the turn variable. (might also be a cause for animation stuttering #59 )

**Comment by wschella** [comment]
I propose splitting this into seperate issues. See #79, #80.

**Comment by tl3ilaxu** [comment]
Agree
