### ISSUE TITLE
Basic viewport

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#30]
Make a viewbox that spans the entire browser screen and contains the entire svg.

**Comment by tl3ilaxu** [comment]
This was broken somehow

**Comment by wschella** [comment]
works on my machine?

**Comment by wschella** [comment]
I guess not, my bad

**Comment by tl3ilaxu** [comment]
Kinda fixed in a841ae6 also kinda not fixed in a841ae6. Will fix soon.

**Comment by tl3ilaxu** [comment]
The viewport should also take into account the orbit sizes of expeditions so they don't fly off screen

**Comment by tl3ilaxu** [comment]
I'd call this a basic viewport, the orbits falling out of screen is more of a homann issue
