### ISSUE TITLE
Homann transfers

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#33]
Change the path an expedition takes to another planet form a straight line to an elliptical orbit.
See: [Homann transfer](http://jwilson.coe.uga.edu/EMAT6680Fa05/Bacon/hohmanntransfers.html)

**Comment by tl3ilaxu** [comment]
Do the homann tweens with bezier approximations

**Comment by wschella** [comment]
If this proves too difficult, i think straight lines are very fine for now. In both cases some visual clues about the path the ship will take might be required, for example a dotted line along the trajectory, and/or a smoke trail coming from the rocket.

**Comment by tl3ilaxu** [comment]
I will get rid of the last bugs in the homann code, then i'll have a look at #55

**Comment by tl3ilaxu** [comment]
Current bug being worked on:

The orbits center point is off due to me not putting the time into actually calculating the difference in planet radii. This in turn moves the foci to the wrong spot and so the point where the expedition leaves(or enters) planetary orbit is slightly off.

**Comment by tl3ilaxu** [comment]
Currently also a bug where the total distance from the log is different form the visualizer calculated distance. The transfers get into invalid states and fly backwards and to completely wrong orbit join points.
