### ISSUE TITLE
Improve resources

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#34]
Make the visuals have one style so they fit together.

**Comment by wschella** [comment]
I propose less detailed, more vector-like planets.
IIRC @werthen had an idea for some CSS stuffs to automatically generate terrain features.

**Comment by werthen** [comment]
Perlin Noise!

**Comment by tl3ilaxu** [comment]
Yes I was also thinking about generating the planets with Perlin noise, however I like the control that planets from images give us. So a combination of the two would be great.

**Comment by werthen** [comment]
I want to try something with svg's, should be possible and only adequately complex, but we'll see

**Comment by iasoon** [comment]
I think complex css features will make the whole thing a bit sluggish. What I'd suggest is having some 'surface svg' that contains some terrain features etc, then colour this in the controlling players colour for clarity.

**Comment by wschella** [comment]
Your mom is a bit sluggish!

**Comment by tl3ilaxu** [comment]
There is nothing that stops us from generating complex terrain features as a d3 pattern (so multiple surface svgs). We could just generate a few patterns at the start of the visualizer then just use variations (simple rotations or recoloring) of that pattern on multiple planets. This way we can balance how many completely unique planet textures to have and have control over performance. Best of both worlds.

**Comment by tl3ilaxu** [comment]
And indeed iasoons mother has gotten a bit sluggish with age.

**Comment by wschella** [comment]
As part of the solution, I added some planet svg's which we could use. There are plenty of these resources so that we don't have to generate additional noise. Using svg's will also give us more flexibility in the visualizing aspect, as we could easily color the _inside_, scale them better, remove overly attention grabbing features, and thus reduce visual noise from redundant details.
