### ISSUE TITLE
Voronoi  backgrounds

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#43]
Color the background in the color of the player that owns nearby planets. This will make it easier to see what planets are owned by whom.

**Comment by wschella** [comment]
Voronoi diagram style?

**Comment by tl3ilaxu** [comment]
Jep exactly! Was thinking of a weighted rounded Voronoi diagram.

**Comment by tl3ilaxu** [comment]
[That is handy](https://github.com/d3/d3-voronoi/blob/master/README.md#voronoi)

**Comment by iasoon** [comment]
Finished and merged.
