### ISSUE TITLE
Add logging support to the botdriver

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#45]
Currently matches and their results are not logged to something persistent, preventing us from visualizing the game. This is the last bit of functionality the botdriver *really* needs for the MVP I think.

The simplest way to currently do this would be to log each gamestep completely, together with some metadata.

I have 2 proposals for the format:

```
{
  meta_x: x,
  meta_y: y,
  turns: [
    {turn_1}, {turn_2}, ...
  ]
}
```

```
{
  meta_x: x,
  meta_y: y
}\n
{turn_1}\n
{turn_2}\n
...
```
The seconds has the advantage of allowing us to do incremental parsing.

**Comment by wschella** [comment]
@iasoon @tl3ilaxu opinions?

**Comment by tl3ilaxu** [comment]
Neither format has any real advantage or disadvantage. So I think it really comes down to personal opinion. I really don't have a strong preference for either, but I like the first one best.

**Comment by iasoon** [comment]
Definitely the second one, not having incremental parsing would mean you can't stream into the visualizer (which would be a godsend when debugging).

It's called json-stream, by the way.

**Comment by tl3ilaxu** [comment]
As far as I can see we can parse both formats just as easy with json-stream. But I'm OK with the second one too!

**Comment by iasoon** [comment]
Oh, I didn't know JSONStream was a thing! I was thinking of https://en.wikipedia.org/wiki/JSON_Streaming .
Anyways, I am quite positive it is not possible to incrementally parse a JSON object, since its keys are not ordered (that means it is possible you will have to parse the entire payload before getting to the required header data). It might be that there are parsers that ignore this fact, but this is not according to the JSON spec and (imo) quite hacky. 
If I'm wrong, and we can indeed parse JSON objects incrementally, I think just having one JSON object is preferred.

**Comment by tl3ilaxu** [comment]
Yes you are definitely correct, actually the second format will not only be less hacky (yeah incrementally parse a JSON object sounds like a horrible idea) it will also be easier to parse (no crazy JSON paths).

**Comment by feliciaan** [comment]
@iasoon JSON Streaming is indeed the way to go. It's also used in other streaming APIs.

**Comment by iasoon** [comment]
Another small remark: It is probably a good idea to make the first object a 'setup' object, in the general sense. For a 'regular' format this could contain the game info and metadata like Wout drafted, but it should also be used to store the initial state for games where we only record deltas.

**Comment by wschella** [comment]
IMO we should wait with changing to delta's until we have the game up and running and a clear view of what costs en benefits of the logging, as delta's will introduce at least some form of extra complexity. In the very distant future, it should be relatively easy to switch between delta and full gamestates.

**Comment by iasoon** [comment]
@wschella Most certainly. I wanted to emphasize the general structure of the game log format: setup step*, where a step could be a state dump, a delta, or whatever funky alternative someone comes up with.
