### ISSUE TITLE
Create component interaction interfaces

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#5]
This issue will function as an overview for all issues off this type, as each component-relation deserves it's own issue.

- [ ] Filer -> Data store
- [ ] Filer <-> ELO
- [ ] Game server -> Filer
- [ ] Game server <-> Matchmaker
- [ ] Game server <-> Rule set
- [ ] Game server <-> Bot driver
- [ ] Bot driver <-> Bot
- [ ] Arbiter <-> Rule set
- [ ] Client GUI <-> Arbiter
- [ ] Client GUI <-> Visualizer
- [ ] Client GUI <-> Bot driver
- [ ] Web server <- Data store
- [ ] Web server <-> Visualizer

**Comment by iasoon** [comment]
Since this is being materialized in protobuf definitions now, and we're not really tracking this issue anyways, I'll close this.
