### ISSUE TITLE
Add functionality to load map from file

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#51]
Currently, in all matches the map is randomly generated, but for various use-cases (tournaments, monitored play, ...) we want to manually select a map (or multiple) for play. Which map to play should be a config option, and in case none is present, one will generated randomly.

**Comment by iasoon** [comment]
This should probably be solved by passing an array of possible map files in the game config. This allows you pick on which map you want to play (for just one match), and to randomly pick a map from a pre-generated set (for a series of matches, such as a tournament).

**Comment by iasoon** [comment]
Additional caveat: we need a way to specify a 'player position' in a map. This is required because the starting position defines the balance of a map, meaning you can't create a balanced map if you can't control where players start.
