### ISSUE TITLE
Add turn limit to matchconfig and game-implementation

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#52]
We might want to enforce a turn limit for games, and it's the gamerules responsibility to handle it, and act accordingly (although it is also in the interest of the botdriver).

**Comment by iasoon** [comment]
GAMECONFIG

**Comment by wschella** [comment]
MATCHCONFIG, AS YOU CAN SET IT IN THE CONFIG FOR EACH MATCH. No?

**Comment by iasoon** [comment]
THERE IS NO MATCH CONFIG
