### ISSUE TITLE
Migrate bot driver to tokio

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#71]
What the title says.

This will allow us to have easy parallelism in the game server.
We should look into also migrating the botdriver<->gamerules interface to tokio.

**Comment by wschella** [comment]
What would the benefit be of botdriver <-> gamerules in tokio?

**Comment by iasoon** [comment]
@wschella it will allow for way more flexibility. The current API can be implemented on top of such an API, in case we would desire that.

**Comment by wschella** [comment]
Valid point.

**Comment by iasoon** [comment]
To elaborate on this: if my understanding of this matter is correct, letting the game implementation handle futures will allow it to make decisions about time-outs and other communication errors, instead of having to do this in the framework (and thus limit the implementations in what is possible).

**Comment by wschella** [comment]
While I agree that this adds flexibility, we should watch out we don't put too much mandatory responsibility in the hands of the game implementation.

**Comment by iasoon** [comment]
@wschella I suggest solving this by adding library functions that wrap a simple implementation to provide a complete game implementation. For example, we could create a SimpleGame struct that takes an instance of the current Game trait as an argument, and handles all complexities for you using some sane defaults.

I agree that mandatory responsibility is not desirable, but opt-in responsibility is key to providing a flexible framework.

**Comment by iasoon** [comment]
Since the tokio branch has now been merged in planetwars-total, I'll close this issue.
