### ISSUE TITLE
Previous turns

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#73]
Somewhere the persistent planet map was broken. Now we cannot go back a turn with the visualizer. This is because the last turns planet objects get deleted and the expeditions don't know where to go.

**Comment by tl3ilaxu** [comment]
The turn object keeps its own planet map. This object is destroyed after the turn and that is the issue.

**Comment by tl3ilaxu** [comment]
The assumption was made that planets won't change during the game (as in no new planets or removal of planets). Should we go back to a static map of planets or should we keep all previous turn objects alive?

**Comment by wschella** [comment]
I feel like we can keep planets and players static.

**Comment by iasoon** [comment]
Doesn't d3 handle this? You can bind the data each turn, with planet names as keys, no?
