### ISSUE TITLE
rewrite views in a front-end framework

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#90]
Guys this is just horrible right now

**Comment by wschella** [comment]
To expand on this issue, the way the views work now is neither a scalable nor practical solution. For instance, it's difficult to use the visualizer both in the blockly-client, as well as standalone. We should use some front-end framework (Node, Vue, etc.) to expand on the tooling available and increase reusability.

**Comment by wschella** [comment]
I obviously mean React instead of Node.

**Comment by iasoon** [comment]
I'd suggest React for no real reason - I have used both shortly in the past, and I liked react more. Unless anybody else has input, I'd suggest to just get started with it?

**Comment by iasoon** [comment]
Progress on this: we rewrote about 90% of the visualizer as a react component.
TODO: end card and score view. Please do poke me if you want to work on this! It's not that much work nor difficult, just porting some code in the same way that has already been done :-)

**Comment by iasoon** [comment]
Yay, this has been done!
