### ISSUE TITLE
Colors on the map and in the scoreboard are switched

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#91]
[]
![bug](https://user-images.githubusercontent.com/9478856/30751894-08ab82f8-9fbb-11e7-8b72-aa933693d478.PNG)

**Comment by tl3ilaxu** [comment]
This has to do with the scoreboard not updating when a new game starts

**Comment by iasoon** [comment]
Are you certain? The scoreboard does seem to be updated, as sometimes there are two drawn on top of each other.

This is probably a result of poor refactoring under time stress, we should look into further cleaning up code (and possibly #90).
