### ISSUE TITLE
New blockly blocks

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#92]
We should think on new blocks to add or perhaps template blocks to make to make bot creating easier for the user.

**Comment by tl3ilaxu** [comment]
A block that could prove useful: a way to easily differentiate between owned and enemy planets.

This could be two new blocks: owned planets or enemy planets. Or as suggested we could make it a dropdown: planets: mine | enemy | neutral

**Comment by tl3ilaxu** [comment]
A while block could also come in handy

**Comment by iasoon** [comment]
Do we want functions, or does this overcomplicate things?

**Comment by tl3ilaxu** [comment]
I'm not sure if functions would be a good idea, we should first see how our code evolves with other added blocks before trying to add functions.

**Comment by wschella** [comment]
Not a fan of functions, but I am even more of a 'do-every-turn-block', basically what is hidden now and added by the runner or something. It would provide more visual information of what we expect from them.

**Comment by redfast00** [comment]
- A sort block would be nice (for example to loop over planets in order of distance).

**Comment by wschella** [comment]
@redfast00: i am very much a fan of that idea.

**Comment by Str-Gen** [comment]
A top-N query: e.g. The n closest planets, the n planets with the least troops, ...

**Comment by Str-Gen** [comment]
A minimax block. Minimize variable A while maximizing variable B or the other way around etc. (for at least 2 variables)

**Comment by iasoon** [comment]
@Str-Gen Could you elaborate how such a min-max block should behave?

**Comment by Str-Gen** [comment]
There is a block: element in ... that minimizes | maximizes ...
It would be nice to get an element that minimizes A and maximizes B, or minimizes and minimizes, ... 
(the closest planet may not be the easiest to conquer (in terms of opposition) or the planet with the lowest shipcount may be far away). Currently there is no way to implement logic that can solve this problem.

**Comment by redfast00** [comment]
@Str-gen: how do you want this to work? Have a float between 0 and 1 to choose what property to prefer?

**Comment by Str-Gen** [comment]
That would be one option. However, there may be a best solution which can be found by using calculus.
https://math.oregonstate.edu/home/programs/undergrad/CalculusQuestStudyGuides/vcalc/min_max/min_max.html

**Comment by Str-Gen** [comment]
@redfast00 Je hebt normaalgezien een Zeus account gekregen en kan je nu registreren op slack om mee in de loop te zijn, bedank @R13N :) 
ik zal dit bericht verwijderen aangezien het off-topic is

**Comment by iasoon** [comment]
@str-gen this does not make sense to me. How do you minimize one variable while maximizing another one? The link you provide relates to functions of multiple variables, how is that relevant?

**Comment by Str-Gen** [comment]
Apologies, the link is only useful for problems in 2 variables where there is a mathematical relation between the two. The result of that problem gives the optimal values for the 2 variables to attain a certain pre-specified goal. (max / min)
The overall best strategy to play may be found by using techniques for mulit-objective optimization.

**Comment by Silox** [comment]
@Str-Gen: Could you give a practical example? This might help to understand the need.

**Comment by iasoon** [comment]
I implemented allegiance filters for planets and expeditions, and a sort block was added.
Feel free to reopen for further requests.
