### ISSUE TITLE
Sometimes the blockly code page doesn't refresh

### ISSUE THREAD

**Issue by tl3ilaxu** [ZeusWPI/MOZAIC#93]
No idea why, cannot consistently reproduce

**Comment by iasoon** [comment]
I encountered this issue as well.

I noticed it occurs less frequently when you sacrifice a goat or two, though.

**Comment by tl3ilaxu** [comment]
BLOOD FOR THE BLOODGOAT

**Comment by tl3ilaxu** [comment]
This has something to do with resizing, if the code window is blank, resizing the frame fixes it.

**Comment by iasoon** [comment]
Ah! Resizing the window will probably cause blockly to rerender. We could manually make blockly rerender the workspace when we switch back to the workspace.

**Comment by tl3ilaxu** [comment]
There we go then adding a render call when switching should fix it.
