### ISSUE TITLE
Use only last bot-version in botpool

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#96]
Currently we are saving the bot every time he wins against his opponent, but we should check against bots with the same name *and* the same code to prevent the same bot being added umpteen times.
Not a real implementation of a botpool, but quite easy to implement.

**Comment by wschella** [comment]
I think a better solution would be to add only the last  succesful bot of a player to the botpool.

**Comment by iasoon** [comment]
bot == username here, I assume?

**Comment by wschella** [comment]
Yes.

**Comment by iasoon** [comment]
That would mean that people can overwrite bots belonging to other people. Is this what we want?

**Comment by wschella** [comment]
Yes, it's gud enough, we'll just make them not be assholes on live events

**Comment by redfast00** [comment]
If the default username (sadeerstejaars) is chosen by more then two users, won't they overwrite each others bots?

**Comment by iasoon** [comment]
@redfast00 that is correct.

**Comment by wschella** [comment]
Indeed, i propose removing the default, and refining the name input from an annoying popup to something sensible

**Comment by myncke** [comment]
We still need a form and validation.
